// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPHSS.Repository.Models;

[Table("Dashboard")]
public partial class Dashboard
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("reportId")]
    public Guid ReportId { get; set; }

    [Required]
    [Column("metricName")]
    [StringLength(255)]
    public string MetricName { get; set; }

    [Column("metricValue")]
    [StringLength(255)]
    public string MetricValue { get; set; }

    [Column("metricCategory")]
    public double? MetricCategory { get; set; }

    [Column("isDeleted")]
    public bool? IsDeleted { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("updateAt", TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [ForeignKey("ReportId")]
    [InverseProperty("Dashboards")]
    public virtual Report Report { get; set; }
}