// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPHSS.Repository.Models;

[Table("Report")]
public partial class Report
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Required]
    [Column("type")]
    [StringLength(50)]
    public string Type { get; set; }

    [Required]
    [Column("tittle")]
    [StringLength(255)]
    public string Tittle { get; set; }

    [Column("description")]
    public string Description { get; set; }

    [Column("totalScore")]
    public double? TotalScore { get; set; }

    [Column("status")]
    [StringLength(50)]
    public string Status { get; set; }

    [Column("startDate")]
    public DateOnly? StartDate { get; set; }

    [Column("endDate")]
    public DateOnly? EndDate { get; set; }

    [Column("note")]
    public string Note { get; set; }

    [Column("isDeleted")]
    public bool? IsDeleted { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("updateAt", TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [InverseProperty("Report")]
    public virtual ICollection<Dashboard> Dashboards { get; set; } = new List<Dashboard>();
}